
"""
This code was automatically generated by openapi-dataclass.py.
"""

from functools import wraps
from typing import TypedDict, Literal

from .api_call import api_call

def api_func(old_func):
    @wraps(old_func)
    def new_func(*args, **kwargs):
        url, params = old_func(*args, **kwargs)
        return api_call(url, params)
    return new_func

__all__ = ['GetDepartureBoard', 'GetArrivalBoard', 'GetArrivalDepartureBoard', 'GetArrBoardWithDetails', 'GetDepBoardWithDetails', 'GetArrDepBoardWithDetails', 'GetFastestDepartures', 'GetFastestDeparturesWithDetails', 'GetNextDepartures', 'GetNextDeparturesWithDetails', 'GetServiceDetails']

class StationBoard(TypedDict):
    trainServices: list['ServiceItem']
    busServices: list['ServiceItem']
    ferryServices: list['ServiceItem']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class ServiceItem(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    formation: 'FormationData'
    futureCancellation: bool
    futureDelay: bool
    diversion: 'ServiceItemDiversion'
    origin: list['ServiceLocation']
    destination: list['ServiceLocation']
    currentOrigins: list['ServiceLocation']
    currentDestinations: list['ServiceLocation']
    rsid: str
    sta: str
    eta: str
    std: str
    etd: str
    platform: str
    operator: str
    operatorCode: str
    isCircularRoute: bool
    isCancelled: bool
    filterLocationCancelled: bool
    serviceType: Literal['train', 'bus', 'ferry']
    length: str
    detachFront: bool
    isReverseFormation: bool
    cancelReason: str
    delayReason: str
    serviceID: str
    adhocAlerts: list[str]

class XmlSerializerNamespaces(TypedDict):
    Count: str

class NRCCMessage(TypedDict):
    Value: str

class UncertaintyType(TypedDict):
    reason: str
    status: Literal['Delay', 'Cancellation', 'Other']

class FormationData(TypedDict):
    loadingCategory: 'LoadingCategory'
    coaches: list['CoachData']

class ServiceItemDiversion(TypedDict):
    reason: str
    divertedVia: str
    between: 'ServiceItemDiversionBetween'
    rerouteDelay: str

class ServiceLocation(TypedDict):
    locationName: str
    crs: str
    via: str
    futureChangeTo: str
    assocIsCancelled: bool

class LoadingCategory(TypedDict):
    code: str
    colour: str
    image: str
    Value: str

class CoachData(TypedDict):
    coachClass: str
    toilet: 'ToiletAvailabilityType'
    loading: str
    loadingSpecified: bool
    number: str

class ServiceItemDiversionBetween(TypedDict):
    start: 'ServiceItemDiversionBetweenStart'
    end: 'ServiceItemDiversionBetweenEnd'

class ToiletAvailabilityType(TypedDict):
    status: Literal['Unknown', 'InService', 'NotInService']
    Value: str

class ServiceItemDiversionBetweenStart(TypedDict):
    crs: str
    Value: str

class ServiceItemDiversionBetweenEnd(TypedDict):
    crs: str
    Value: str

class StationBoardWithDetails(TypedDict):
    trainServices: list['ServiceItemWithCallingPoints']
    busServices: list['ServiceItemWithCallingPoints']
    ferryServices: list['ServiceItemWithCallingPoints']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class ServiceItemWithCallingPoints(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    previousCallingPoints: list['ArrayOfCallingPoints']
    subsequentCallingPoints: list['ArrayOfCallingPoints']
    formation: 'FormationData'
    futureCancellation: bool
    futureDelay: bool
    diversion: 'ServiceItemDiversion'
    origin: list['ServiceLocation']
    destination: list['ServiceLocation']
    currentOrigins: list['ServiceLocation']
    currentDestinations: list['ServiceLocation']
    rsid: str
    sta: str
    eta: str
    std: str
    etd: str
    platform: str
    operator: str
    operatorCode: str
    isCircularRoute: bool
    isCancelled: bool
    filterLocationCancelled: bool
    serviceType: Literal['train', 'bus', 'ferry']
    length: str
    detachFront: bool
    isReverseFormation: bool
    cancelReason: str
    delayReason: str
    serviceID: str
    adhocAlerts: list[str]

class ArrayOfCallingPoints(TypedDict):
    callingPoint: list['CallingPoint']
    serviceType: Literal['train', 'bus', 'ferry']
    serviceChangeRequired: bool
    assocIsCancelled: bool

class CallingPoint(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    locationName: str
    crs: str
    st: str
    et: str
    at: str
    isCancelled: bool
    length: str
    detachFront: bool
    formation: 'FormationData'
    adhocAlerts: list[str]
    cancelReason: str
    delayReason: str
    affectedByDiversion: bool
    rerouteDelay: str

class DeparturesBoard(TypedDict):
    departures: list['DepartureItem']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class DepartureItem(TypedDict):
    service: 'ServiceItem'
    crs: str

class DeparturesBoardWithDetails(TypedDict):
    departures: list['DepartureItemWithCallingPoints']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class DepartureItemWithCallingPoints(TypedDict):
    service: 'ServiceItemWithCallingPoints'
    crs: str

class ServiceDetails(TypedDict):
    adhocAlerts: list[str]
    formation: 'FormationData'
    previousCallingPoints: list['ArrayOfCallingPoints']
    subsequentCallingPoints: list['ArrayOfCallingPoints']
    generatedAt: str
    serviceType: Literal['train', 'bus', 'ferry']
    locationName: str
    crs: str
    operator: str
    operatorCode: str
    rsid: str
    isCancelled: bool
    cancelReason: str
    delayReason: str
    overdueMessage: str
    length: str
    detachFront: bool
    isReverseFormation: bool
    platform: str
    sta: str
    eta: str
    ata: str
    std: str
    etd: str
    atd: str
    divertedVia: str
    diversionReason: str
    Xmlns: 'XmlSerializerNamespaces'

@api_func
def GetDepartureBoard(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoard:
    """Returns all public departures for the supplied CRS code within a defined time window."""
    return ('/GetDepartureBoard/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetArrivalBoard(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoard:
    """Returns all public arrivals for the supplied CRS code within a defined time window."""
    return ('/GetArrivalBoard/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetArrivalDepartureBoard(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoard:
    """Returns all public arrivals and departures for the supplied CRS code within a defined time window"""
    return ('/GetArrivalDepartureBoard/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetArrBoardWithDetails(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoardWithDetails:
    """Returns all public arrivals for the supplied CRS code within a defined time window, including service details."""
    return ('/GetArrBoardWithDetails/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetDepBoardWithDetails(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoardWithDetails:
    """Returns all public departures for the supplied CRS code within a defined time window, including service details."""
    return ('/GetDepBoardWithDetails/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetArrDepBoardWithDetails(crs, numRows=10, filterCrs=None, filterType='to', timeOffset=0, timeWindow=120) -> StationBoardWithDetails:
    """Returns all public arrivals and departures for the supplied CRS code within a defined time window, including service details."""
    return ('/GetArrDepBoardWithDetails/{crs}'.format(crs=crs), {'numRows': numRows, 'filterCrs': filterCrs, 'filterType': filterType, 'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetFastestDepartures(crs, filterList, timeOffset=0, timeWindow=120) -> DeparturesBoard:
    """Returns the public departure for the supplied CRS code within a defined time window to the locations specified in the filter with the earliest arrival time at the filtered location."""
    return ('/GetFastestDepartures/{crs}/{filterList}'.format(crs=crs, filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetFastestDeparturesWithDetails(crs, filterList, timeOffset=0, timeWindow=120) -> DeparturesBoardWithDetails:
    """Returns the public departure for the supplied CRS code within a defined time window to the locations specified in the filter with the earliest arrival time at the filtered location, including service details."""
    return ('/GetFastestDeparturesWithDetails/{crs}/{filterList}'.format(crs=crs, filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetNextDepartures(crs, filterList, timeOffset=0, timeWindow=120) -> DeparturesBoard:
    """Returns the next public departure for the supplied CRS code within a defined time window to the locations specified in the filter."""
    return ('/GetNextDepartures/{crs}/{filterList}'.format(crs=crs, filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetNextDeparturesWithDetails(crs, filterList, timeOffset=0, timeWindow=120) -> DeparturesBoardWithDetails:
    """Returns the next public departure for the supplied CRS code within a defined time window to the locations specified in the filter, including service details."""
    return ('/GetNextDeparturesWithDetails/{crs}/{filterList}'.format(crs=crs, filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow})

@api_func
def GetServiceDetails(serviceId) -> ServiceDetails:
    """Returns service details for a specific service identified by a station board. These details are supplied relative to the station board from which the serviceID field value was generated. Service details are only available while the service appears on the station board from which it was obtained. This is normally for two minutes after it is expected to have departed, or after a terminal arrival. If a request is made for a service that is no longer available then a null value is returned."""
    return ('/GetServiceDetails/{serviceId}'.format(serviceId=serviceId), {})
