"""This code was automatically generated by https://github.com/yunruse/openapi-transmog."""
from pathlib import Path
from json import loads
LOOKUP_FILE = Path(__file__).parent / 'lookup.json'
LOOKUP: dict[str, str] = loads(LOOKUP_FILE.read_text())

def get_crs(crs_or_station_name: str):
    if len(crs_or_station_name) == 3:
        return crs_or_station_name.upper()
    stat = crs_or_station_name.lower().strip()
    if stat in LOOKUP:
        return LOOKUP[stat]
    return crs_or_station_name

def entirely_hidden():
    pass
from typing import TypedDict, Literal
from os.path import expandvars
from requests import request
from dotenv import load_dotenv
load_dotenv()

class StationBoard(TypedDict):
    trainServices: list['ServiceItem']
    busServices: list['ServiceItem']
    ferryServices: list['ServiceItem']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class ServiceItem(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    formation: 'FormationData'
    futureCancellation: bool
    futureDelay: bool
    diversion: 'ServiceItemDiversion'
    origin: list['ServiceLocation']
    destination: list['ServiceLocation']
    currentOrigins: list['ServiceLocation']
    currentDestinations: list['ServiceLocation']
    rsid: str
    sta: str
    eta: str
    std: str
    etd: str
    platform: str
    operator: str
    operatorCode: str
    isCircularRoute: bool
    isCancelled: bool
    filterLocationCancelled: bool
    serviceType: Literal['train', 'bus', 'ferry']
    length: int
    detachFront: bool
    isReverseFormation: bool
    cancelReason: str
    delayReason: str
    serviceID: str
    adhocAlerts: list[str]

class XmlSerializerNamespaces(TypedDict):
    Count: int

class NRCCMessage(TypedDict):
    Value: str

class UncertaintyType(TypedDict):
    reason: str
    status: Literal['Delay', 'Cancellation', 'Other']

class FormationData(TypedDict):
    loadingCategory: 'LoadingCategory'
    coaches: list['CoachData']

class ServiceItemDiversion(TypedDict):
    reason: str
    divertedVia: str
    between: 'ServiceItemDiversionBetween'
    rerouteDelay: int

class ServiceLocation(TypedDict):
    locationName: str
    crs: str
    via: str
    futureChangeTo: str
    assocIsCancelled: bool

class LoadingCategory(TypedDict):
    code: str
    colour: str
    image: str
    Value: str

class CoachData(TypedDict):
    coachClass: str
    toilet: 'ToiletAvailabilityType'
    loading: int
    loadingSpecified: bool
    number: str

class ServiceItemDiversionBetween(TypedDict):
    start: 'ServiceItemDiversionBetweenStart'
    end: 'ServiceItemDiversionBetweenEnd'

class ToiletAvailabilityType(TypedDict):
    status: Literal['Unknown', 'InService', 'NotInService']
    Value: str

class ServiceItemDiversionBetweenStart(TypedDict):
    crs: str
    Value: str

class ServiceItemDiversionBetweenEnd(TypedDict):
    crs: str
    Value: str

class StationBoardWithDetails(TypedDict):
    trainServices: list['ServiceItemWithCallingPoints']
    busServices: list['ServiceItemWithCallingPoints']
    ferryServices: list['ServiceItemWithCallingPoints']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class ServiceItemWithCallingPoints(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    previousCallingPoints: list['ArrayOfCallingPoints']
    subsequentCallingPoints: list['ArrayOfCallingPoints']
    formation: 'FormationData'
    futureCancellation: bool
    futureDelay: bool
    diversion: 'ServiceItemDiversion'
    origin: list['ServiceLocation']
    destination: list['ServiceLocation']
    currentOrigins: list['ServiceLocation']
    currentDestinations: list['ServiceLocation']
    rsid: str
    sta: str
    eta: str
    std: str
    etd: str
    platform: str
    operator: str
    operatorCode: str
    isCircularRoute: bool
    isCancelled: bool
    filterLocationCancelled: bool
    serviceType: Literal['train', 'bus', 'ferry']
    length: int
    detachFront: bool
    isReverseFormation: bool
    cancelReason: str
    delayReason: str
    serviceID: str
    adhocAlerts: list[str]

class ArrayOfCallingPoints(TypedDict):
    callingPoint: list['CallingPoint']
    serviceType: Literal['train', 'bus', 'ferry']
    serviceChangeRequired: bool
    assocIsCancelled: bool

class CallingPoint(TypedDict):
    uncertainty: 'UncertaintyType'
    affectedBy: str
    locationName: str
    crs: str
    st: str
    et: str
    at: str
    isCancelled: bool
    length: int
    detachFront: bool
    formation: 'FormationData'
    adhocAlerts: list[str]
    cancelReason: str
    delayReason: str
    affectedByDiversion: bool
    rerouteDelay: int

class DeparturesBoard(TypedDict):
    departures: list['DepartureItem']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class DepartureItem(TypedDict):
    service: 'ServiceItem'
    crs: str

class DeparturesBoardWithDetails(TypedDict):
    departures: list['DepartureItemWithCallingPoints']
    Xmlns: 'XmlSerializerNamespaces'
    generatedAt: str
    locationName: str
    crs: str
    filterLocationName: str
    filtercrs: str
    filterType: Literal['to', 'from']
    nrccMessages: list['NRCCMessage']
    platformAvailable: bool
    areServicesAvailable: bool

class DepartureItemWithCallingPoints(TypedDict):
    service: 'ServiceItemWithCallingPoints'
    crs: str

class ServiceDetails(TypedDict):
    adhocAlerts: list[str]
    formation: 'FormationData'
    previousCallingPoints: list['ArrayOfCallingPoints']
    subsequentCallingPoints: list['ArrayOfCallingPoints']
    generatedAt: str
    serviceType: Literal['train', 'bus', 'ferry']
    locationName: str
    crs: str
    operator: str
    operatorCode: str
    rsid: str
    isCancelled: bool
    cancelReason: str
    delayReason: str
    overdueMessage: str
    length: int
    detachFront: bool
    isReverseFormation: bool
    platform: str
    sta: str
    eta: str
    ata: str
    std: str
    etd: str
    atd: str
    divertedVia: str
    diversionReason: str
    Xmlns: 'XmlSerializerNamespaces'

def api_call(method: str, url: str, params: dict, annotators: dict={}):
    """Handler for API calls."""
    response = request(method=method, url='https://lite.realtime.nationalrail.co.uk/OpenLDBWS/api/20220120' + url, params=params, auth=('token', expandvars('$LDBWS_TOKEN')))
    if response.status_code in annotators:
        return annotators[response.status_code](response.json())
    response.raise_for_status()
    return response.json()

def GetDepartureBoard(departing_from: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoard:
    """
    Returns all public departures for the supplied CRS code within a defined time window.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetDepartureBoard/{crs}'.format(crs=get_crs(departing_from)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetArrivalBoard(arriving_at: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoard:
    """
    Returns all public arrivals for the supplied CRS code within a defined time window.

    :param arriving_at: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetArrivalBoard/{crs}'.format(crs=get_crs(arriving_at)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetArrivalDepartureBoard(station: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoard:
    """
    Returns all public arrivals and departures for the supplied CRS code within a defined time window

    :param station: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetArrivalDepartureBoard/{crs}'.format(crs=get_crs(station)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetArrBoardWithDetails(arriving_at: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoardWithDetails:
    """
    Returns all public arrivals for the supplied CRS code within a defined time window, including service details.

    :param arriving_at: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetArrBoardWithDetails/{crs}'.format(crs=get_crs(arriving_at)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetDepBoardWithDetails(departing_from: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoardWithDetails:
    """
    Returns all public departures for the supplied CRS code within a defined time window, including service details.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetDepBoardWithDetails/{crs}'.format(crs=get_crs(departing_from)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetArrDepBoardWithDetails(station: str, numRows: int=10, timeOffset: int=0, timeWindow: int=120) -> StationBoardWithDetails:
    """
    Returns all public arrivals and departures for the supplied CRS code within a defined time window, including service details.

    :param station: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param numRows: The number of services to return in the resulting station board.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetArrDepBoardWithDetails/{crs}'.format(crs=get_crs(station)), {'numRows': numRows, 'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetFastestDepartures(departing_from: str, filterList: str, timeOffset: int=0, timeWindow: int=120) -> DeparturesBoard:
    """
    Returns the public departure for the supplied CRS code within a defined time window to the locations specified in the filter with the earliest arrival time at the filtered location.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param filterList: A list of CRS codes of the destinations location to filter, at least 1 but not greater than 15 must be supplied.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetFastestDepartures/{crs}/{filterList}'.format(crs=get_crs(departing_from), filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetFastestDeparturesWithDetails(departing_from: str, filterList: str, timeOffset: int=0, timeWindow: int=120) -> DeparturesBoardWithDetails:
    """
    Returns the public departure for the supplied CRS code within a defined time window to the locations specified in the filter with the earliest arrival time at the filtered location, including service details.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param filterList: A list of CRS codes of the destinations location to filter, at least 1 but not greater than 10 must be supplied.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetFastestDeparturesWithDetails/{crs}/{filterList}'.format(crs=get_crs(departing_from), filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetNextDepartures(departing_from: str, filterList: str, timeOffset: int=0, timeWindow: int=120) -> DeparturesBoard:
    """
    Returns the next public departure for the supplied CRS code within a defined time window to the locations specified in the filter.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param filterList: A list of CRS codes of the destinations location to filter, at least 1 but not greater than 25 must be supplied.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetNextDepartures/{crs}/{filterList}'.format(crs=get_crs(departing_from), filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetNextDeparturesWithDetails(departing_from: str, filterList: str, timeOffset: int=0, timeWindow: int=120) -> DeparturesBoardWithDetails:
    """
    Returns the next public departure for the supplied CRS code within a defined time window to the locations specified in the filter, including service details.

    :param departing_from: The CRS code of the location for which the request is being made. The CRS code must be passed as UPPERCASE
    :param filterList: A list of CRS codes of the destinations location to filter, at least 1 but not greater than 10 must be supplied.
    :param timeOffset: An offset in minutes against the current time to provide the station board for. Defaults to 0. Optional.
    :param timeWindow: How far into the future in minutes, relative to timeOffset, to return services for.
    """
    return api_call('get', '/GetNextDeparturesWithDetails/{crs}/{filterList}'.format(crs=get_crs(departing_from), filterList=filterList), {'timeOffset': timeOffset, 'timeWindow': timeWindow}, {})

def GetServiceDetails(serviceId: str) -> ServiceDetails:
    """
    Returns service details for a specific service identified by a station board. These details are supplied relative to the station board from which the serviceID field value was generated. Service details are only available while the service appears on the station board from which it was obtained. This is normally for two minutes after it is expected to have departed, or after a terminal arrival. If a request is made for a service that is no longer available then a null value is returned.
    :param serviceId: The LDBWS service ID of the service to request the details of. The service ID is obtained from a service listed in a StationBoard object returned from any other request.
    """
    return api_call('get', '/GetServiceDetails/{serviceId}'.format(serviceId=serviceId), {}, {})
__all__ = ['GetDepartureBoard', 'GetArrivalBoard', 'GetArrivalDepartureBoard', 'GetArrBoardWithDetails', 'GetDepBoardWithDetails', 'GetArrDepBoardWithDetails', 'GetFastestDepartures', 'GetFastestDeparturesWithDetails', 'GetNextDepartures', 'GetNextDeparturesWithDetails', 'GetServiceDetails']
